name: alfred_endpoints_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  build:
  source_gen:
  alfred_endpoints:
    path: ../alfred_endpoints
  analyzer: ^6.3.0
  alfred: ^1.1.1
  code_builder: ^4.8.0
  build_runner: ^2.4.7
  glob: ^2.1.2
  path: ^1.9.0
  dart_style: ^2.3.4

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
