name: example_models
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-174.2.beta

# Add regular dependencies here.
dependencies:
  dart_mappable: ^4.1.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.7
  dart_mappable_builder: ^4.1.0
  lints: ^3.0.0
  test: ^1.24.0
