name: example_server
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0-174.2.beta

# Add regular dependencies here.
dependencies:
  example_models:
    path: ../example_models
  alfred: ^1.1.1
  alfred_api_annotation:
    path: ../../../alfred_api_annotation

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  alfred_api:
    path: ../../
