name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.2

dependencies:
  alfred: ^1.1.1
  alfred_endpoints:
    path: ../

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  alfred_endpoints_generator:
    path: ../../alfred_endpoints_generator
  build_runner: ^2.4.7
